---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[s3cmd::default]
    attributes:
      s3cmd:
        user: vagrant
        config_dir: /home/vagrant
        data_bag: {
          name: 'aws_creds',
          item: 's3_user'
        }